// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace SH1ProjeUygulamasi.Data.CompiledModels
{
    public partial class DatabaseContextModel
    {
        private DatabaseContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("bb20d881-9250-4353-a8e6-6a10087d115b"), entityTypeCount: 4)
        {
        }

        partial void Initialize()
        {
            var category = CategoryEntityType.Create(this);
            var product = ProductEntityType.Create(this);
            var slider = SliderEntityType.Create(this);
            var user = UserEntityType.Create(this);

            ProductEntityType.CreateForeignKey1(product, category);

            CategoryEntityType.CreateAnnotations(category);
            ProductEntityType.CreateAnnotations(product);
            SliderEntityType.CreateAnnotations(slider);
            UserEntityType.CreateAnnotations(user);

            AddAnnotation("ProductVersion", "9.0.9");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
