// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using SH1ProjeUygulamasi.Data;
using SH1ProjeUygulamasi.Data.CompiledModels;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(DatabaseContext), typeof(DatabaseContextModel))]
